name: CI

on: [push]

jobs:
  build_lint_prettier:
    name: Build, Lint, Prettier
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Prettier
        run: npx prettier --check src/**/*.ts{,x}
      #- name: Test
      #  run: npm run test
